baseURL = 'https://blog.littlegiving.org/'
canonifyurls = true
languageCode = 'en-gb'
title = 'Little Giving Blog'
theme = ['littlegiving']
disableKinds = ["home", "taxonomy", "term"]
ignoreErrors = ["error-disable-taxonomy"]
buildFuture = true
[permalinks]
  posts = '/:filename'